// SPDX-License-Identifier: Apache-2.0

// Command vendorregister generates the vendor due-diligence pack's register
// entries (docs/vendor-dd/register/) from the vendor facts file: a canonical
// batch a customer imports into its own register, its adapter manifest, and
// a README listing the facts still pending. A fact that is null is left out
// of the batch (missing, never invented). Run it from the repository root.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Dir is where the facts are read and the files written.
var Dir = filepath.Join("docs", "vendor-dd", "register")

// Fact is one statement of the vendor about itself.
type Fact struct {
	Value *string `json:"value"`
	Note  string  `json:"note"`
}

// Facts is vendor-facts.json.
type Facts struct {
	Status   string          `json:"status"`
	Version  string          `json:"version"`
	Product  string          `json:"product"`
	Provider map[string]Fact `json:"provider"`
}

// fieldOrder is the order of the ict_provider fields the vendor states.
var fieldOrder = []string{"lei", "legal_name", "name_latin", "person_type", "hq_country", "currency", "parent_id_code", "parent_id_type"}

const (
	adapterName = "vendor-dd-pack"
	providerID  = "vendor:nexops-one"
	sourceRef   = "docs/vendor-dd/register/vendor-facts.json"
)

// Generate returns the generated files by name.
func Generate(f Facts) (map[string][]byte, []string, error) {
	for k := range f.Provider {
		known := false
		for _, o := range fieldOrder {
			known = known || o == k
		}
		if !known {
			return nil, nil, fmt.Errorf("vendor-facts.json: unknown provider fact %q", k)
		}
	}
	rec := map[string]any{}
	var pending []string
	for _, k := range fieldOrder {
		fact, ok := f.Provider[k]
		if !ok || fact.Value == nil || strings.TrimSpace(*fact.Value) == "" {
			pending = append(pending, k)
			continue
		}
		if k == "lei" {
			continue
		}
		rec[k] = *fact.Value
	}
	if lei := f.Provider["lei"].Value; lei != nil && *lei != "" {
		rec["provider_id_code"], rec["provider_id_type"] = *lei, "LEI"
	} else {
		rec["provider_id_code"] = providerID
	}
	rec["_meta"] = map[string]any{"source_record_ref": sourceRef}
	supplies := []string{"provider_id_code"}
	for _, k := range fieldOrder {
		if k == "lei" {
			supplies = append(supplies, "provider_id_type")
		} else {
			supplies = append(supplies, k)
		}
	}
	sort.Strings(supplies)
	supplies = dedupe(supplies)
	manifest := map[string]any{"name": adapterName, "version": f.Version, "schema_version": "0.1.0",
		"supplies": map[string][]string{"ict_provider": supplies}, "modes": []string{"full"}}
	batch := map[string]any{
		"schema_version": "0.1.0",
		"batch":          map[string]any{"batch_id": "vendor-dd@" + f.Version, "mode": "full"},
		"source":         map[string]any{"system": "nexops-one-vendor-dd-pack", "adapter": adapterName, "adapter_version": f.Version},
		"entities":       map[string]any{"ict_provider": []any{rec}},
	}
	out := map[string][]byte{}
	for name, v := range map[string]any{"manifest.json": manifest, "nexops-one-register.json": batch} {
		data, err := json.MarshalIndent(v, "", "  ")
		if err != nil {
			return nil, nil, err
		}
		out[name] = append(data, '\n')
	}
	out["README.md"] = readme(f, pending)
	return out, pending, nil
}

func dedupe(s []string) []string {
	var out []string
	for i, v := range s {
		if i == 0 || v != s[i-1] {
			out = append(out, v)
		}
	}
	return out
}

func readme(f Facts, pending []string) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "<!-- Generated by 'go run ./internal/tools/vendorregister' from vendor-facts.json. Do not edit. -->\n\n")
	b.WriteString("Status: pending legal review\n\n")
	b.WriteString("# Register entries of " + f.Product + "\n\n")
	b.WriteString("Customers who use " + f.Product + " record its supplier in their DORA register of information\n" +
		"(template B_05.01, ICT third-party service providers). This folder gives that entry as a canonical\n" +
		"batch, so it can be imported as it is instead of being retyped:\n\n")
	b.WriteString("| File | Content |\n|---|---|\n")
	b.WriteString("| `nexops-one-register.json` | a full-mode canonical batch with one `ict_provider` record |\n")
	b.WriteString("| `manifest.json` | the manifest of its adapter, `" + adapterName + "` |\n")
	b.WriteString("| `vendor-facts.json` | the facts it is generated from |\n\n")
	b.WriteString("## Import\n\n```bash\ncompliance-engine validate nexops-one-register.json\n")
	b.WriteString("curl -X PUT \"$URL/api/v1/adapters/" + adapterName + "/manifest\" -H \"Authorization: Bearer $TOKEN\" --data-binary @manifest.json\n")
	b.WriteString("curl -X POST \"$URL/api/v1/ingestions\" -H \"Authorization: Bearer $TOKEN\" --data-binary @nexops-one-register.json\n```\n\n")
	b.WriteString("The batch is full-mode for its own adapter: importing a newer version replaces this record and touches\n" +
		"nothing else in the register. The customer then adds what only it knows, referring to the provider code\n" +
		"of the record: the contractual arrangement (B_02.01), the service lines with the functions supported\n" +
		"(B_02.02, B_06.01) and its own assessment of the service (B_07.01).\n\n")
	b.WriteString("The product is software the customer runs itself (self-hosted, or embedded in NEXOPS ONE in the\n" +
		"customer's environment): it stores and processes no customer data on the vendor's side, so there are no\n" +
		"data locations, subcontractors (B_05.02) or service lines to declare from the vendor's side for these\n" +
		"modes. A hosted offering, when it exists, will add them (see [../subprocessors.md](../subprocessors.md)).\n\n")
	b.WriteString("## Pending facts\n\n")
	if len(pending) == 0 {
		b.WriteString("None: every fact is stated.\n")
	} else {
		b.WriteString("These facts are not established yet. They are left out of the batch, so the customer's completeness\n" +
			"view shows them as missing; they are never filled with guesses. Complete `vendor-facts.json` and\n" +
			"regenerate before publishing the pack.\n\n| Fact | Note |\n|---|---|\n")
		for _, k := range pending {
			fmt.Fprintf(&b, "| `%s` | %s |\n", k, f.Provider[k].Note)
		}
	}
	return b.Bytes()
}

func main() {
	data, err := os.ReadFile(filepath.Join(Dir, "vendor-facts.json"))
	if err == nil {
		var f Facts
		dec := json.NewDecoder(bytes.NewReader(data))
		dec.DisallowUnknownFields()
		if err = dec.Decode(&f); err == nil {
			var files map[string][]byte
			var pending []string
			if files, pending, err = Generate(f); err == nil {
				for name, content := range files {
					if err = os.WriteFile(filepath.Join(Dir, name), content, 0o644); err != nil {
						break
					}
					fmt.Println("wrote", filepath.Join(Dir, name))
				}
				fmt.Printf("%d fact(s) pending: %s\n", len(pending), strings.Join(pending, ", "))
			}
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "vendorregister:", err)
		os.Exit(1)
	}
}
