// SPDX-License-Identifier: Apache-2.0

// Package docgen renders the reference documents in docs/reference from
// the code: the configuration variables, the canonical fields, the control
// catalogs, and the roles and permissions. compliance-engine docs gen writes
// them, and TestGeneratedDocsUpToDate fails when the committed files differ.
package docgen

import (
	"bytes"
	"context"
	"fmt"
	"sort"
	"strings"

	"github.com/nexops-one/compliance-engine/pkg/access"
	"github.com/nexops-one/compliance-engine/pkg/catalog"
	"github.com/nexops-one/compliance-engine/pkg/config"
	"github.com/nexops-one/compliance-engine/pkg/crypt"
	"github.com/nexops-one/compliance-engine/sdk/schema"
)

// Banner starts every generated document.
const Banner = "<!-- Generated by 'compliance-engine docs gen'. Do not edit: change the code and regenerate. -->\n\n"

// Inputs are what the documents are generated from.
type Inputs struct {
	Schema   *schema.Schema
	Catalogs []*catalog.Catalog // every loaded version, in reference order
}

// Generate returns the reference documents by file name.
func Generate(in Inputs) (map[string][]byte, error) {
	fields, err := canonicalFields(in.Schema)
	if err != nil {
		return nil, err
	}
	return map[string][]byte{
		"configuration.md":    configuration(),
		"canonical-fields.md": fields,
		"catalogs.md":         catalogs(in.Catalogs),
		"roles.md":            roles(),
	}, nil
}

// cell escapes text for a Markdown table cell.
func cell(s string) string {
	s = strings.ReplaceAll(strings.TrimSpace(s), "\n", " ")
	return strings.ReplaceAll(s, "|", `\|`)
}

func yes(b bool) string {
	if b {
		return "yes"
	}
	return ""
}

func configuration() []byte {
	return ConfigurationTable("Configuration reference",
		"`compliance-engine serve` (and `demo`) read their configuration from these environment variables. "+
			"Empty or unset variables take the default. Invalid values stop the server at start with every error listed.",
		config.Variables())
}

// ConfigurationTable renders a configuration reference document, for the
// open core and for editions' own variables.
func ConfigurationTable(title, intro string, vars []config.Variable) []byte {
	var b bytes.Buffer
	b.WriteString(Banner)
	b.WriteString("# " + title + "\n\n")
	b.WriteString(intro + "\n\n")
	b.WriteString("| Variable | Default | Purpose |\n|---|---|---|\n")
	for _, v := range vars {
		def := "(empty)"
		if v.Default != "" {
			def = "`" + v.Default + "`"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", v.Name, def, cell(v.Doc))
	}
	return b.Bytes()
}

func canonicalFields(s *schema.Schema) ([]byte, error) {
	sens, err := crypt.LoadSensitivity(s.Version)
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString(Banner)
	fmt.Fprintf(&b, "# Canonical fields (schema %s)\n\n", s.Version)
	b.WriteString("Every entity and field of the canonical data model. **Key** marks the record identity; ")
	b.WriteString("**Export** marks fields the register of information requires (missing ones make controls `not_assessed`), ")
	b.WriteString("**Conditional** those that may legitimately not apply; **Sensitive** fields are encrypted at rest when a key is configured ")
	b.WriteString("and never appear in Profile B reports. The register references are indicative (pending legal review).\n\n")
	for _, name := range s.EntityNames() {
		e, _ := s.Entity(name)
		fmt.Fprintf(&b, "## `%s`\n\n", name)
		if e.Title != "" {
			fmt.Fprintf(&b, "%s\n\n", cell(e.Title))
		}
		b.WriteString("| Field | Type | Register reference | Key | Export | Conditional | Sensitive | Codelist or reference | Description |\n")
		b.WriteString("|---|---|---|---|---|---|---|---|---|\n")
		for _, fn := range e.FieldNames {
			f := e.Fields[fn]
			typ := f.Type
			if f.Format != "" {
				typ += " (" + f.Format + ")"
			}
			ref := f.Codelist
			if f.References != "" {
				ref = "→ " + f.References
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s | %s | %s | %s |\n", fn, typ, f.RoIRef, yes(f.IsIdentity()),
				yes(f.RoIRequired), yes(f.RoIConditional), yes(sens.Has(name, fn)), cell(ref), cell(f.Description))
		}
		b.WriteString("\n")
	}
	return b.Bytes(), nil
}

func ruleText(r catalog.Rule) string {
	parts := []string{string(r.Kind)}
	if r.Entity != "" {
		parts = append(parts, "on `"+r.Entity+"`")
	}
	if r.Field != "" {
		parts = append(parts, fmt.Sprintf("`%s` = `%v`", r.Field, r.Value))
	}
	if len(r.Fields) > 0 {
		parts = append(parts, "fields `"+strings.Join(r.Fields, "`, `")+"`")
	}
	if r.Min > 0 {
		parts = append(parts, fmt.Sprintf("at least %d", r.Min))
	}
	return strings.Join(parts, " ")
}

func catalogs(cs []*catalog.Catalog) []byte {
	var b bytes.Buffer
	b.WriteString(Banner)
	b.WriteString("# Control catalogs\n\n")
	b.WriteString("The catalogs built into this version. Their content is indicative, pending legal review. ")
	b.WriteString("Score counts the statuses in *counts as ready*; coverage is the share of in-scope controls that are assessable.\n\n")
	for _, c := range cs {
		fmt.Fprintf(&b, "## %s %s (`%s`)\n\n", c.Framework, c.Version, c.Ref())
		fmt.Fprintf(&b, "- Jurisdiction: %s; effective %s; schema %s\n", c.Jurisdiction, c.EffectiveDate, c.SchemaVersion)
		fmt.Fprintf(&b, "- Source: %s\n", cell(c.SourceAuthority))
		fmt.Fprintf(&b, "- Counts as ready: %s\n", strings.Join(c.Scoring.CountsAsReady, ", "))
		if c.Scoring.ReviewInterval != "" {
			fmt.Fprintf(&b, "- Default review interval: %s\n", c.Scoring.ReviewInterval)
		}
		b.WriteString("\n| Control | Title | Rule | Requires | Evidence expected |\n|---|---|---|---|---|\n")
		for _, ctl := range c.Controls {
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s |\n", ctl.ID, cell(ctl.Title), cell(ruleText(ctl.Rule)),
				cell(strings.Join(ctl.Requires, ", ")), cell(strings.Join(ctl.EvidenceRequirements, "; ")))
		}
		b.WriteString("\n")
	}
	return b.Bytes()
}

func roles() []byte {
	var b bytes.Buffer
	b.WriteString(Banner)
	b.WriteString("# Roles and permissions\n\n")
	b.WriteString("Roles are granted per workspace and are additive. Every API route and console action requires one permission ")
	b.WriteString("(`x-permission` in the OpenAPI definition).\n\n")
	b.WriteString("| Role | Purpose |\n|---|---|\n")
	for _, r := range access.AllRoles() {
		fmt.Fprintf(&b, "| `%s` | %s |\n", r, cell(access.Describe(r)))
	}
	b.WriteString("\n## Permission matrix\n\n| Permission |")
	for _, r := range access.AllRoles() {
		fmt.Fprintf(&b, " %s |", r)
	}
	b.WriteString("\n|---|")
	for range access.AllRoles() {
		b.WriteString("---|")
	}
	b.WriteString("\n")
	for _, p := range access.Permissions() {
		fmt.Fprintf(&b, "| %s |", p)
		for _, r := range access.AllRoles() {
			mark := " "
			if access.Allows([]access.Role{r}, p) {
				mark = "✓"
			}
			fmt.Fprintf(&b, " %s |", mark)
		}
		b.WriteString("\n")
	}
	return b.Bytes()
}

// Names lists the generated file names in order.
func Names(docs map[string][]byte) []string {
	out := make([]string, 0, len(docs))
	for n := range docs {
		out = append(out, n)
	}
	sort.Strings(out)
	return out
}

// Default returns the inputs of this build: the latest embedded schema and
// every embedded catalog version.
func Default(ctx context.Context) (Inputs, error) {
	reg, err := schema.Default()
	if err != nil {
		return Inputs{}, err
	}
	cs, err := catalog.Embedded().Catalogs(ctx)
	if err != nil {
		return Inputs{}, err
	}
	set, err := catalog.NewSet(reg, cs)
	if err != nil {
		return Inputs{}, err
	}
	in := Inputs{Schema: reg.Latest()}
	for _, ref := range set.Refs() {
		c, _ := set.Get(ref)
		in.Catalogs = append(in.Catalogs, c)
	}
	return in, nil
}
